
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;

int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng + (yy_more_offset) >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( &yytext[(yy_more_offset)], (yytext_ptr), yyleng + 1 ); \
	yyleng += (yy_more_offset); \
	(yy_prev_more_offset) = (yy_more_offset); \
	(yy_more_offset) = 0; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[241] =
    {   0,
       77,   76,   65,   76,   64,   76,   76,   75,   76,   76,
        6,   76,   76,   66,   76,    5,   76,   62,   76,   62,
       76,   62,   76,   62,   76,   62,   76,   62,   76,   62,
       76,   62,   76,   62,   76,   62,   76,   62,   76,   76,
       65,   63,   66,   68,   67,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   20,   62,   62,   62,
       62,   62,   67,   73,   70,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   74,
       71,   72,   69,   28,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   13,   62,   12,   62,   62,    3,   62,

       60,   62,   61,    7,   62,   27,   62,   62,   62,   62,
        4,   62,   26,   62,   62,   13,   62,   12,   62,   62,
       60,   62,    2,   62,   62,   62,   62,   62,   62,   62,
       62,   56,   62,   62,   62,   62,   55,   62,   19,   43,
       46,   11,   15,    1,   22,   62,   29,   62,   62,   62,
       62,   62,   62,   62,   56,   62,   62,   62,   62,   55,
       62,   15,   32,   38,   21,   24,    1,   62,   49,   62,
       62,   62,   62,   41,   62,   62,   62,   54,   62,    8,
       31,   17,   35,   34,   36,   39,   62,   49,   62,   62,
       62,   48,   62,   47,   62,   53,   62,   57,   62,   54,

       62,   44,   40,    9,   30,   25,   62,   51,   62,   62,
       48,   62,   47,   62,   53,   62,   57,   62,   18,   33,
       16,   14,   52,   62,   62,   42,   45,   37,   62,   42,
       23,   62,   10,   58,   62,   50,   62,   50,   62,   59
    } ;

static yyconst flex_int16_t yy_accept[405] =
    {   0,
        1,    1,    1,    2,    3,    5,    7,    8,   10,   11,
       13,   14,   16,   18,   20,   22,   24,   26,   28,   30,
       32,   34,   36,   38,   40,   41,   42,   43,   43,   43,
       44,   45,   46,   46,   46,   47,   48,   49,   50,   51,
       52,   53,   54,   55,   56,   57,   59,   60,   61,   62,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   64,   64,   64,   64,   65,   65,   66,   67,   68,
       69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
       79,   80,   80,   80,   80,   80,   80,   80,   80,   80,

       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   81,   81,   82,   82,   83,   83,   84,   86,   87,
       88,   89,   90,   91,   92,   93,   94,   96,   98,   99,
      101,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  106,  108,  109,  110,  111,  113,  115,  116,  118,
      120,  121,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,

      123,  123,  123,  123,  123,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  125,  126,  127,  128,  129,
      130,  131,  132,  134,  135,  136,  137,  139,  139,  139,
      139,  139,  140,  141,  141,  141,  141,  141,  142,  142,
      143,  143,  143,  143,  143,  143,  143,  143,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      145,  147,  149,  150,  151,  152,  153,  154,  155,  157,
      158,  159,  160,  162,  162,  162,  162,  162,  162,  162,
      162,  162,  162,  162,  162,  162,  162,  162,  162,  162,
      163,  163,  163,  163,  164,  164,  165,  166,  167,  167,

      167,  167,  168,  169,  171,  172,  173,  174,  176,  177,
      178,  180,  180,  180,  180,  180,  180,  181,  181,  181,
      182,  183,  184,  185,  185,  186,  186,  186,  186,  186,
      187,  187,  187,  187,  187,  188,  190,  191,  192,  194,
      196,  198,  200,  202,  202,  202,  203,  203,  203,  204,
      204,  204,  204,  204,  204,  205,  206,  206,  206,  207,
      208,  210,  211,  213,  215,  217,  219,  220,  220,  220,
      220,  220,  221,  222,  223,  223,  223,  223,  225,  226,
      227,  227,  227,  228,  228,  229,  229,  230,  231,  231,
      231,  231,  232,  233,  233,  234,  235,  236,  236,  238,

      238,  240,  241,  241
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    1,    1,
        1,    6,    7,    8,    7,    9,   10,   11,   11,   11,
       12,   11,   11,   11,   11,   13,   11,    1,    1,    1,
       14,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       10,    1,    1,    1,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   37,   64,
       65,   66,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    3,    2,
        3,    3,    3,    1,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[421] =
    {   0,
        0,  268,  272, 1063,  265, 1063,  255, 1063,   58, 1063,
       61,   66, 1063,   33,    0,   64,   41,   57,   58,   63,
       79,   60,   52,   73,  128,  224, 1063,  208,   89,  118,
      121,  179,  188,  195,    0,   59,   78,   66,  110,  126,
      118,  144,  155,  141,  177,    0,  184,  169,  175,  177,
      176,  176,  187,  195,  189,  210,  188,  205,  195,  220,
      217,  233,  222,  217,  222,  238,  229,  245,  258,  275,
      281,  290,  297,   92,  294,  300,  303,  267,  122,  262,
      302,  285,  285,  288,  302,  303,  307,  302,  295,  311,
      302,  298,  307,  315,  308,  304,  321,  305,  320,  322,

      311,  314,  312,  311,  337,  320,  319,  348,  337,  356,
      340,  357,  343,  359,  355,  357,  369,  353,  359,  376,
      379,  383,  395,  403,  406,  410,  413,    0,  371,  408,
      401,  395,   87,  397,  414,  401,  425,  430,   81,    0,
      435,  403,  415,  430,  434,  415,  417,  423,  430, 1063,
      432,  432,  436,  448,  432,  468,  441,  441,  454,  467,
      464,  474,  455,  453,  460,  458,  464,  472,  484,  479,
        0,    0,  483,  484,  518,    0,    0,  496,  506,  530,
      564,  543,  499,   77,  504,  514,  527,  529,  527,  539,
      527,  526,  536,  547,  545,  544,  545,  541,  552,  568,

      556,  576,  568,  566, 1063,  584,  567,  571,  569,  588,
      588,  589,  580,  596,  602,  603,  603,  601,  605,  598,
      599,  601,  632,  613,  411,  609,  656,  632,  616,  635,
      626, 1063, 1063,  641,  630,  644,  627, 1063,  648, 1063,
      637,  653,  656,  642,  645,  652,  650,    0,  666,  664,
      657,  656,  656,  673,  662,  678,  663,  672,  668,    0,
        0,    0,  678,  674,  675,  687,  680,  694,  719,  682,
      686,  704,  732,  690,  703,  700,  719,  731,  715,  718,
      734,  736,  707,  729,  738,  728,  722,  744,  743,    0,
      749,  751,  733, 1063,  736, 1063, 1063, 1063,  749,  755,

      752,    0,  740,  791,  759,  751,  773,    0,  750,  770,
      799,  765,  776,  799,  798,  799, 1063,  786,  795, 1063,
     1063, 1063, 1063,  787, 1063,  790,  791,  798,  801, 1063,
      809,  806,  796,  801,  814,  826,  801,  809,  853,  859,
      864,  869,  874,  844,  857, 1063,  861,  857, 1063,  874,
      857,  859,  860,  865, 1063, 1063,  870,  874, 1063,  866,
        0,  865,  918,  923,  928,  933, 1063,  892,  913,  914,
      921, 1063, 1063, 1063,  920,  930,  921,    0,  919,    0,
      925,  925, 1063,  926, 1063,  928,  938,    0,  928,  927,
      941, 1063,  930,  943, 1063, 1063,  934,  940,  987,  954,

      992, 1063, 1063, 1032, 1034, 1036, 1038, 1040, 1042, 1044,
      103,   86, 1046, 1048, 1050, 1052, 1054, 1056,   84, 1058
    } ;

static yyconst flex_int16_t yy_def[421] =
    {   0,
      403,    1,  403,  403,  403,  403,  404,  403,  403,  403,
      403,  403,  403,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  403,  403,  403,  404,  403,  403,
      403,  403,  403,  403,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  406,  407,  405,  405,
      408,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      405,  405,  405,  405,  405,  405,  405,  405,  406,  407,
      405,  408,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  405,  405,  405,  405,  405,  405,
      405,  405,  409,  405,  405,  405,  410,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  411,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  412,
      405,  405,  405,  405,  405,  405,  405,  405,  409,  405,
      405,  405,  410,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  411,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  412,  405,  413,  405,  405,  405,  405,  405,  405,
      414,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  405,  413,  405,  405,  415,  416,
      417,  418,  414,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  405,
      405,  405,  415,  416,  417,  418,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  405,  405,  419,
      403,  403,  403,  403,  403,  403,  405,  419,  403,  403,
      403,  403,  405,  403,  403,  403,  405,  403,  420,  403,

      420,  403,    0,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403
    } ;

static yyconst flex_int16_t yy_nxt[1130] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,    4,
       12,   12,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   15,   21,   15,   15,   15,   15,   22,   15,   15,
       15,   15,   15,   23,   15,   15,   15,   15,   15,   24,
        4,   14,   15,   16,   17,   18,   19,   20,   15,   21,
       15,   15,   15,   15,   22,   15,   15,   15,   15,   15,
       23,   15,   15,   15,   15,   24,   29,   36,   30,   30,
       30,   31,   31,   31,   32,   37,   30,   30,   30,   39,
       43,   44,   40,   33,   34,   41,   42,  388,   48,  302,
       49,   50,   78,   45,   36,   79,   46,   80,   38,   31,

       31,   31,   75,   75,   75,   39,  290,   43,   44,   40,
       33,   34,   41,   42,   47,   48,   49,  229,   50,   78,
       45,  181,   79,   46,   80,   38,   32,  175,   30,   30,
       30,   31,   31,   31,  129,   33,   34,   81,   69,   70,
       82,   47,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   83,   61,   62,   63,   64,   65,   84,   66,
       67,   68,   33,   34,   81,   69,   70,   82,   86,   51,
       52,   53,   54,   55,   56,   57,   58,   59,   60,   83,
       61,   62,   63,   64,   65,   84,   66,   67,   68,   71,
       71,   71,   85,   87,   74,   86,   72,   73,   75,   75,

       75,   76,   88,   89,   90,   77,   77,   77,   91,   92,
       93,   27,   94,   97,   99,   95,  100,   98,   85,  105,
       87,   96,  108,   72,   73,   26,  101,  106,  102,   88,
       89,   90,  103,  107,  109,   91,   92,   93,  104,   94,
       97,   99,   95,  100,   98,  110,  105,  111,   96,  108,
      112,  113,  101,  114,  106,  102,  115,  116,   27,  103,
      107,  109,  117,  118,  120,  104,   26,  119,  121,  121,
      121,  403,  110,   25,  111,  403,  403,  112,  113,  403,
      114,  122,  403,  115,  116,  123,  123,  123,  403,  117,
      118,   71,   71,   71,  119,  128,  124,  130,   72,   73,

      125,  125,  125,  126,   75,   75,   75,  127,  127,  127,
       77,   77,   77,   77,   77,   77,  131,  132,  133,  134,
      135,  136,  128,  137,  130,   72,   73,  138,  139,  140,
      141,  142,  143,  144,  145,  146,  147,  148,  149,  150,
      151,  152,  154,  131,  132,  133,  134,  135,  136,  153,
      137,  155,  156,  157,  138,  139,  140,  141,  142,  143,
      144,  145,  146,  147,  148,  149,  150,  151,  152,  154,
      158,  159,  160,  161,  162,  153,  163,  164,  155,  156,
      157,  165,  166,  167,  168,  169,  121,  121,  121,  121,
      121,  121,  170,  123,  123,  123,  403,  158,  159,  160,

      161,  162,  171,  163,  164,  123,  123,  123,  165,  166,
      167,  168,  169,  125,  125,  125,  125,  125,  125,  170,
      127,  127,  127,  127,  127,  127,  172,  173,  174,  171,
      176,  177,  178,   35,  183,   35,   35,   35,   35,  184,
       35,   35,   35,   35,  185,   35,   35,   35,  271,  186,
      187,  188,  189,  172,  173,  174,  190,  176,  177,  178,
      191,  183,  192,  193,  194,   35,  184,  195,  403,  403,
       35,  185,  200,  201,  271,   35,  186,  187,  188,  189,
      202,  203,  204,  190,  207,  208,  196,  191,  209,  192,
      193,  194,  205,  210,  195,  197,  198,  211,  212,  200,

      201,  199,  213,  206,  214,  215,  216,  202,  203,  204,
      222,  207,  208,  196,   35,  209,   35,   35,   35,  205,
      210,  228,  197,  198,  211,  212,  403,  403,  199,  213,
      206,  214,  215,  216,  217,  230,  231,  222,   35,  218,
       35,   35,   35,  403,  219,  232,   35,  220,  228,  233,
      221,   35,  234,   35,   35,   35,  403,  235,  237,  403,
      238,  217,  230,  231,  239,  240,  218,  241,  236,  242,
       35,  219,  232,  243,  220,  244,  233,  221,  223,  234,
      245,  224,  225,   35,  235,  237,  226,  238,  246,  247,
      248,  239,  240,  249,  241,  236,  242,  250,  251,  227,

      243,  252,  244,  253,  254,  223,  255,  245,  224,  225,
      256,  258,  259,  226,  260,  246,  247,  248,  261,  262,
      249,  263,  257,  264,  250,  251,  227,  265,  252,  266,
      253,  254,  267,  255,  268,  270,  272,  256,  258,  259,
       35,  260,   35,   35,   35,  261,  262,  274,  263,  257,
      264,  275,  276,  277,  265,  278,  266,  279,  280,  267,
      281,  268,  270,  272,   35,  282,   35,   35,   35,  403,
      283,  284,   35,  285,  274,  286,  287,  288,  275,  276,
      277,  289,  278,  291,  279,  280,  292,  281,  293,  294,
      295,  296,  282,  297,  298,  299,   35,  283,  284,  300,

      285,  301,  286,  287,  288,  303,  304,  305,  289,  306,
      291,  307,  308,  292,  309,  293,  294,  295,  296,  310,
      297,  298,  299,  311,  312,  313,  300,   35,  301,   35,
       35,   35,  303,  304,  305,  314,  306,  315,  307,  308,
       35,  309,   35,   35,   35,  321,  310,  316,  317,  318,
      311,  312,  313,  319,  320,  322,  323,  324,  326,   35,
      325,  327,  314,  328,  315,  329,  330,  331,  332,  333,
      334,  321,   35,  335,  316,  317,  318,  337,  338,  341,
      319,  320,  322,  323,  324,  326,  325,  339,  327,  342,
      328,  340,  329,  330,  331,  332,  333,  334,  344,   35,

      335,   35,   35,   35,  337,  338,  341,   35,  345,   35,
       35,   35,  403,  346,  339,  347,  342,  348,  340,  349,
      350,  351,  352,  353,  354,  344,  355,  356,  357,  358,
      359,   35,  360,  361,   35,  345,   35,   35,   35,   35,
      346,  362,  347,  403,  348,  403,  349,  350,  351,  352,
      353,  354,  403,  355,  356,  357,  358,  359,  403,  360,
      361,   35,  367,   35,   35,   35,   35,   35,  362,   35,
       35,   35,   35,  368,   35,   35,   35,   35,  369,   35,
       35,   35,   35,  370,   35,   35,   35,  403,  371,  367,
      372,  373,  374,   35,  375,  376,  377,  378,  379,   35,

      368,  403,  403,  403,   35,  369,  403,  403,  403,   35,
      370,  403,  403,  403,   35,  371,  403,  372,  373,  374,
      380,  375,  376,  377,  378,  379,   35,  381,   35,   35,
       35,   35,  382,   35,   35,   35,   35,  383,   35,   35,
       35,   35,  384,   35,   35,   35,  403,  380,  385,  386,
      387,  389,  390,  391,  381,  392,  393,  394,   35,  382,
      395,  396,  397,   35,  383,  398,  399,  400,   35,  384,
      403,  403,  403,   35,  402,  385,  386,  387,  389,  390,
      391,  403,  392,  393,  394,  403,  403,  395,  396,  397,
      403,  403,  398,  399,  400,   35,  403,   35,   35,   35,

       35,  402,   35,   35,   35,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,   35,  403,  403,
      403,  403,   35,   28,   28,   28,   35,   35,  179,  179,
      180,  180,  182,  182,  269,  269,  273,  273,  336,  336,
      343,  343,  363,  363,  364,  364,  365,  365,  366,  366,
      401,  401,    3,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403
    } ;

static yyconst flex_int16_t yy_chk[1130] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,   14,    9,    9,
        9,   11,   11,   11,   12,   16,   12,   12,   12,   17,
       19,   20,   18,   12,   12,   18,   18,  419,   22,  412,
       23,   24,   36,   21,   14,   37,   21,   38,   16,   29,

       29,   29,   74,   74,   74,   17,  411,   19,   20,   18,
       12,   12,   18,   18,   21,   22,   23,  184,   24,   36,
       21,  139,   37,   21,   38,   16,   30,  133,   30,   30,
       30,   31,   31,   31,   79,   30,   30,   39,   31,   31,
       40,   21,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   41,   25,   25,   25,   25,   25,   42,   25,
       25,   25,   30,   30,   39,   31,   31,   40,   44,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   41,
       25,   25,   25,   25,   25,   42,   25,   25,   25,   32,
       32,   32,   43,   45,   33,   44,   32,   32,   33,   33,

       33,   34,   47,   48,   49,   34,   34,   34,   50,   51,
       52,   28,   53,   54,   55,   53,   55,   54,   43,   57,
       45,   53,   59,   32,   32,   26,   55,   58,   56,   47,
       48,   49,   56,   58,   60,   50,   51,   52,   56,   53,
       54,   55,   53,   55,   54,   61,   57,   62,   53,   59,
       63,   64,   55,   65,   58,   56,   66,   67,    7,   56,
       58,   60,   67,   68,   69,   56,    5,   68,   69,   69,
       69,    3,   61,    2,   62,    0,    0,   63,   64,    0,
       65,   70,    0,   66,   67,   70,   70,   70,    0,   67,
       68,   71,   71,   71,   68,   78,   72,   80,   71,   71,

       72,   72,   72,   73,   75,   75,   75,   73,   73,   73,
       76,   76,   76,   77,   77,   77,   81,   82,   83,   84,
       85,   86,   78,   87,   80,   71,   71,   88,   89,   90,
       91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
      101,  102,  104,   81,   82,   83,   84,   85,   86,  103,
       87,  105,  106,  107,   88,   89,   90,   91,   92,   93,
       94,   95,   96,   97,   98,   99,  100,  101,  102,  104,
      108,  109,  110,  111,  112,  103,  113,  114,  105,  106,
      107,  115,  116,  117,  118,  119,  120,  120,  120,  121,
      121,  121,  119,  122,  122,  122,    0,  108,  109,  110,

      111,  112,  129,  113,  114,  123,  123,  123,  115,  116,
      117,  118,  119,  124,  124,  124,  125,  125,  125,  119,
      126,  126,  126,  127,  127,  127,  130,  131,  132,  129,
      134,  135,  136,  137,  142,  137,  137,  137,  138,  143,
      138,  138,  138,  141,  144,  141,  141,  141,  225,  145,
      146,  147,  148,  130,  131,  132,  149,  134,  135,  136,
      151,  142,  152,  153,  154,  137,  143,  155,    0,    0,
      138,  144,  157,  158,  225,  141,  145,  146,  147,  148,
      159,  160,  161,  149,  163,  164,  156,  151,  165,  152,
      153,  154,  162,  166,  155,  156,  156,  167,  168,  157,

      158,  156,  169,  162,  170,  173,  174,  159,  160,  161,
      178,  163,  164,  156,  179,  165,  179,  179,  179,  162,
      166,  183,  156,  156,  167,  168,    0,    0,  156,  169,
      162,  170,  173,  174,  175,  185,  186,  178,  180,  175,
      180,  180,  180,    0,  175,  187,  179,  175,  183,  188,
      175,  182,  189,  182,  182,  182,    0,  190,  191,    0,
      192,  175,  185,  186,  193,  194,  175,  195,  190,  196,
      180,  175,  187,  197,  175,  198,  188,  175,  181,  189,
      199,  181,  181,  182,  190,  191,  181,  192,  200,  201,
      202,  193,  194,  203,  195,  190,  196,  204,  206,  181,

      197,  207,  198,  208,  209,  181,  210,  199,  181,  181,
      211,  212,  213,  181,  214,  200,  201,  202,  215,  216,
      203,  217,  211,  218,  204,  206,  181,  219,  207,  220,
      208,  209,  221,  210,  222,  224,  226,  211,  212,  213,
      223,  214,  223,  223,  223,  215,  216,  228,  217,  211,
      218,  229,  230,  231,  219,  234,  220,  235,  236,  221,
      237,  222,  224,  226,  227,  239,  227,  227,  227,    0,
      241,  242,  223,  243,  228,  244,  245,  246,  229,  230,
      231,  247,  234,  249,  235,  236,  250,  237,  251,  252,
      253,  254,  239,  255,  256,  257,  227,  241,  242,  258,

      243,  259,  244,  245,  246,  263,  264,  265,  247,  266,
      249,  267,  268,  250,  270,  251,  252,  253,  254,  271,
      255,  256,  257,  272,  274,  275,  258,  269,  259,  269,
      269,  269,  263,  264,  265,  276,  266,  277,  267,  268,
      273,  270,  273,  273,  273,  283,  271,  278,  279,  280,
      272,  274,  275,  281,  282,  284,  285,  286,  288,  269,
      287,  289,  276,  291,  277,  292,  293,  295,  299,  300,
      301,  283,  273,  303,  278,  279,  280,  305,  306,  309,
      281,  282,  284,  285,  286,  288,  287,  307,  289,  310,
      291,  307,  292,  293,  295,  299,  300,  301,  312,  304,

      303,  304,  304,  304,  305,  306,  309,  311,  313,  311,
      311,  311,    0,  314,  307,  315,  310,  316,  307,  318,
      319,  324,  326,  327,  328,  312,  329,  331,  332,  333,
      334,  304,  335,  337,  336,  313,  336,  336,  336,  311,
      314,  338,  315,    0,  316,    0,  318,  319,  324,  326,
      327,  328,    0,  329,  331,  332,  333,  334,    0,  335,
      337,  339,  344,  339,  339,  339,  336,  340,  338,  340,
      340,  340,  341,  345,  341,  341,  341,  342,  347,  342,
      342,  342,  343,  348,  343,  343,  343,    0,  350,  344,
      351,  352,  353,  339,  354,  357,  358,  360,  362,  340,

      345,    0,    0,    0,  341,  347,    0,    0,    0,  342,
      348,    0,    0,    0,  343,  350,    0,  351,  352,  353,
      368,  354,  357,  358,  360,  362,  363,  369,  363,  363,
      363,  364,  370,  364,  364,  364,  365,  371,  365,  365,
      365,  366,  375,  366,  366,  366,    0,  368,  376,  377,
      379,  381,  382,  384,  369,  386,  387,  389,  363,  370,
      390,  391,  393,  364,  371,  394,  397,  398,  365,  375,
        0,    0,    0,  366,  400,  376,  377,  379,  381,  382,
      384,    0,  386,  387,  389,    0,    0,  390,  391,  393,
        0,    0,  394,  397,  398,  399,    0,  399,  399,  399,

      401,  400,  401,  401,  401,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  399,    0,    0,
        0,    0,  401,  404,  404,  404,  405,  405,  406,  406,
      407,  407,  408,  408,  409,  409,  410,  410,  413,  413,
      414,  414,  415,  415,  416,  416,  417,  417,  418,  418,
      420,  420,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[77] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_offset = 0;
static int yy_prev_more_offset = 0;
#define yymore() ((yy_more_offset) = yy_flex_strlen( yytext ))
#define YY_NEED_STRLEN
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET \
	{ \
	(yy_more_offset) = (yy_prev_more_offset); \
	yyleng -= (yy_more_offset); \
	}
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <iostream>
#include "../Solvers.d/ConstData.h"
#include "../Parser.d/auxx.h"
#include "../Parser.d/y.tab.h"
int line_num = 1;
#line 919 "lex.yy.c"

#define INITIAL 0

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 18 "lexer.l"

#line 1103 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 404 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1063 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = (yy_prev_more_offset); yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 19 "lexer.l"
{return TITLE;    }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "lexer.l"
{ fprintf(stderr,"Reading Nodes\n"); return NODE;    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "lexer.l"
{return TYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "lexer.l"
{return EPART;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "lexer.l"
{return EQUALSIGN;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 29 "lexer.l"
{return COMMA;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 31 "lexer.l"
{return ET_SOLID;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 33 "lexer.l"
{ fprintf(stderr,"Reading Elements\n"); return ELEMENT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "lexer.l"
{ fprintf(stderr,"Reading Materials\n"); return MATERIAL;    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "lexer.l"
{ fprintf(stderr,"Reading Disp BC\n"); return DISP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "lexer.l"
{ fprintf(stderr,"Reading Force BC\n");return FORCE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 41 "lexer.l"
{ fprintf(stderr,"Reading Initial Velocity\n");return IVEL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 43 "lexer.l"
{ fprintf(stderr,"Reading Initial Accelerate\n");return IACC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "lexer.l"
{ fprintf(stderr,"Reading Initial Stress\n");return ISTR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "lexer.l"
{ fprintf(stderr,"Set Large \n");return JAUMA; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "lexer.l"
{ fprintf(stderr,"Set Large \n");return HOURGLASS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "lexer.l"
{ fprintf(stderr,"Set Gravity \n");return GRAV; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "lexer.l"
{ fprintf(stderr,"Reading Attribute \n");return ATT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 55 "lexer.l"
{ fprintf(stderr,"Reading Curve \n");return CURVE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "lexer.l"
{ return ID; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "lexer.l"
{ fprintf(stderr,"Set Solver Type \n");return SOLV; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "lexer.l"
{ return DYNA; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "lexer.l"
{ fprintf(stderr,"Set computate time \n");return TERM; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "lexer.l"
{ fprintf(stderr,"Set computate time \n");return STATICTERM; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "lexer.l"
{ fprintf(stderr,"Set timestep \n");return TIMESTEP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "lexer.l"
{  return TIMESTEP_FIXED;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "lexer.l"
{  return TIMESTEP_CURVE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 73 "lexer.l"
{   return TIMESTEP_AUTO;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 75 "lexer.l"
{   return MT_ELASTIC;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 77 "lexer.l"
{ fprintf(stderr,"Reading Pressure \n");return PRESSURE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 79 "lexer.l"
{ fprintf(stderr,"Reading Boundary Condition \n");return FIXED; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "lexer.l"
{ fprintf(stderr,"Set Output info \n");return OUTPUT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 83 "lexer.l"
{ fprintf(stderr,"Set Output info \n");return HISOUTPUT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "lexer.l"
{ fprintf(stderr,"Set Output info \n");return HISNODE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "lexer.l"
{ fprintf(stderr,"Set Element Historty Output info \n");return HISELEM;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "lexer.l"
{ fprintf(stderr,"Set Output info \n");return HISTORY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "lexer.l"
{ fprintf(stderr,"Set Status info \n");return STATUSFILE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "lexer.l"
{ fprintf(stderr,"Set Output info \n");return REMOVE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "lexer.l"
{ fprintf(stderr,"Set NODE Part \n");return NODEPART;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 97 "lexer.l"
{ fprintf(stderr,"Set ELEMENT Part \n");return ELEMPART;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 99 "lexer.l"
{ fprintf(stderr,"GENERATE \n");return GENERATE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 101 "lexer.l"
{ fprintf(stderr,"Set Output info \n");return BULK_VISCOSITY;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 103 "lexer.l"
{ fprintf(stderr,"Set Output info \n");return DEBUGFLG;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 105 "lexer.l"
{ fprintf(stderr,"Clear The Displacement and vilocity \n");return CLEARDVFLG;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "lexer.l"
{ fprintf(stderr,"Export to Flac3D\n");return EXPORTFLAC;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 109 "lexer.l"
{ fprintf(stderr,"set FENQQ\n");return FENQUPL;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 "lexer.l"
{yylval.ival = TypeInfo::Stress;     return EOUTPUTID; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 112 "lexer.l"
{yylval.ival= TypeInfo::Strain;     return EOUTPUTID; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 113 "lexer.l"
{yylval.ival= TypeInfo::History;     return EOUTPUTID; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 114 "lexer.l"
{yylval.ival=TypeInfo::PrinStress;     return EOUTPUTID; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 115 "lexer.l"
{yylval.ival=TypeInfo::PrinMises; return EOUTPUTID;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 116 "lexer.l"
{yylval.ival=TypeInfo::Center; return EOUTPUTID;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 118 "lexer.l"
{yylval.ival=TypeInfo::displacement;    return NOUTPUTID; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "lexer.l"
{yylval.ival = TypeInfo::interforce ;    return NOUTPUTID; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 120 "lexer.l"
{yylval.ival = TypeInfo::velocity ;    return NOUTPUTID; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 121 "lexer.l"
{yylval.ival = TypeInfo::accelerate;    return NOUTPUTID; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 122 "lexer.l"
{yylval.ival = TypeInfo::exterforce;    return NOUTPUTID; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 "lexer.l"
{  return LOCALDAMP; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 126 "lexer.l"
{  return LOCALDAMP; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return ZERO;    }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "lexer.l"
{ fprintf(stderr,"End Reading Input File\n"); return END;  }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "lexer.l"
{ yylval.strval = strdup(yytext); return STRNAME; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 134 "lexer.l"
{ yytext[yyleng-1] = 0; yylval.strval = strdup(yytext+1);
                           return STRNAME; }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 137 "lexer.l"
{ line_num++; /* Count line numbers */ return NewLine; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "lexer.l"
/* Just discard spaces */
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 141 "lexer.l"
{yylval.ival = atoi(yytext) ; return IntConstant ; }
	YY_BREAK
case 67:
#line 144 "lexer.l"
case 68:
#line 145 "lexer.l"
case 69:
#line 146 "lexer.l"
case 70:
#line 147 "lexer.l"
case 71:
YY_RULE_SETUP
#line 147 "lexer.l"
{
       yylval.fval = atof(yytext) ; return DblConstant ; }
	YY_BREAK
case 72:
#line 151 "lexer.l"
case 73:
#line 152 "lexer.l"
case 74:
YY_RULE_SETUP
#line 152 "lexer.l"
{
       int il;
       for(il = 0; yytext[il] != 'd' && yytext[il] != 'D';) ++il;
       yytext[il] = 'e'; yylval.fval = atof(yytext) ; return DblConstant ; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 157 "lexer.l"
{ while(yyinput() != '\n') ; line_num++; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 159 "lexer.l"
ECHO;
	YY_BREAK
#line 1574 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 404 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 404 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 403);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 159 "lexer.l"


void
yyerror(const char  *s)
{
 fprintf(stderr,"%s\n",s);
 fprintf(stderr,"Syntax Error near line %d : %s\n", line_num,yytext);
}

int yywrap()
{
 return 0;
}

